PackageIdentifier: deafsquad.UpdateLoxone
PackageVersion: 0.8.0
InstallerLocale: en-US
InstallerType: msi
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/deafsquad/UpdateLoxone/releases/download/v0.8.0/UpdateLoxone-v0.8.0.msi
    InstallerSha256: 827EB861625DE78302FC66E8B0E2DDE130843A775F17A9B27C849D10D972EC34
    ProductCode: '{00000000-0000-0000-0000-000000000000}'
ManifestType: installer
ManifestVersion: 1.6.0
