PackageIdentifier: deafsquad.UpdateLoxone
PackageVersion: 0.7.9
InstallerLocale: en-US
InstallerType: msi
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/deafsquad/UpdateLoxone/releases/download/v0.7.9/UpdateLoxone-v0.7.9.msi
    InstallerSha256: 2A519941B84ECBE20BCD2FFEE7008AFC7C0A26954E47B0C05CABD67B71E0C944
    ProductCode: '{00000000-0000-0000-0000-000000000000}'
ManifestType: installer
ManifestVersion: 1.6.0
